#!/usr/bin/env node

var debug = require('debug')('my-application');
var app = require('./app');

app.set('port', process.env.PORT || 8080);


var server = app.listen(app.get('port'), function() {
  console.log("Server is listening on port:" + server.address().port);
  debug('Express server listening on port ' + server.address().port);
});


var io = require('socket.io').listen(server);
io.on('connection', function(socket){


});
io.
